name: Deploy to Heroku
on: [ workflow_dispatch ]
jobs:
  deploy-to-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "nakov-mvc-node-app"
          heroku_email:  ${{secrets.HEROKU_EMAIL}}
